config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/IdentityPython/SATOSA:
      branch: master
      repo: https://github.com/IdentityPython/SATOSA
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/IdentityPython/SATOSA git:
        commands:
        - /usr/bin/env sh .sqa/script.maroon_practical_pelican.sh
        container: qc.acc_glaucous_industrious_panda
  QC.Doc:
    repos:
      github.com/IdentityPython/SATOSA find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.caramel_adaptable_goat.sh
        container: qc.doc_copper_organized_warthog
      github.com/IdentityPython/SATOSA git:
        commands:
        - /usr/bin/env sh .sqa/script.brown_confused_anaconda.sh
        container: qc.doc_pineapple_aware_gorilla
      github.com/IdentityPython/SATOSA markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.periwinkle_mindful_lobster.sh
        container: qc.doc_ginger_persistent_mink
      github.com/IdentityPython/SATOSA restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.saffron_warm_lemur.sh
        container: qc.doc_clementine_impulsive_spider
  QC.Lic:
    repos:
      github.com/IdentityPython/SATOSA licensee:
        commands:
        - /usr/bin/env sh .sqa/script.white_enthusiastic_ocelot.sh
        container: qc.lic_amethyst_agile_emu
  QC.Sec:
    repos:
      github.com/IdentityPython/SATOSA bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lemon_feisty_coyote.sh
        container: qc.sec_copper_dramatic_lionfish
  QC.Sty:
    repos:
      github.com/IdentityPython/SATOSA flake8:
        commands:
        - /usr/bin/env sh .sqa/script.jasmine_witty_kangaroo.sh
        container: qc.sty_dusk_creative_marmoset
      github.com/IdentityPython/SATOSA hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flint_impulsive_pangolin.sh
        container: qc.sty_moss_stubborn_chimpanzee
  QC.Uni:
    repos:
      github.com/IdentityPython/SATOSA pytest:
        commands:
        - /usr/bin/env sh .sqa/script.vermilion_radiant_piranha.sh
        container: qc.uni_viridian_loving_newt
  QC.Ver:
    repos:
      github.com/IdentityPython/SATOSA get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.emerald_brilliant_salamander.sh
        container: qc.ver_gold_whimsical_peacock
timeout: 5400
